version: "3.7"

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  rails:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api/:/usr/src/app/
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx:
    image: nginx
    ports:
      - 1337:80
    depends_on:
      - rails
